name: Build and test

on:
  push:
    branches:
      - main
      - develop
      - feature_*

  pull_request:
    branches:
      - develop
      - feature_*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all
    container:
      image: ghcr.io/aosedge/aos-core-build-base:latest
      options: '--entrypoint /usr/bin/bash'
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
    steps:
      # Apply solution to "HOME is overridden for containers" problem: https://github.com/actions/runner/issues/863
      - name: Preserve $HOME set in the container
        run: echo HOME=/root >> "$GITHUB_ENV"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Static analysis
        run: |
          cppcheck --enable=all --inline-suppr -I src -I external/aos_core_common_cpp/include \
          --std=c++17 --error-exitcode=1 --suppressions-list=./suppressions.txt src

      - name: Build and test
        run: |
          mkdir build

          conan profile detect --force

          conan install ./conan/ --output-folder build --settings=build_type=Debug --build=missing
          cmake ./ -B./build/ -DCMAKE_TOOLCHAIN_FILE=./conan_toolchain.cmake \
            -DWITH_CORELIB=ON -DWITH_TEST=ON -DWITH_VCHAN=OFF -DWITH_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug

          cd build
          make; make tests; make coverage

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: build/Testing/Temporary/LastTest.log
          if-no-files-found: ignore

      - name: Upload codecov report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/coverage.total
